---
kind: pipeline
name: default

trigger:
  event:
    - push

steps:
  - name: python3
    image: python:3.7
    commands:
      - pip install tox
      - tox -e py37

  - name: lint
    image: python:3.7
    commands:
      - pip install tox
      - tox -e flake8
